# AI RAG System Configuration

######################### Mandatory Configuration #########################

# Azure OpenAI Configuration in case you want to use Azure OpenAI
azure:
  api_version: 2025-04-01-preview
  deployment: model
  embedding_deployment: text-embedding-3-small

# Gemini Configuration in case you want to use Gemini
gemini:
  model: gemini-2.5-flash
  embedding_model: models/embedding-001

# Provider Configuration
# Set to 'azure' or 'gemini' to choose the AI provider you previsouly set (above)
providers:
  llm: "gemini" # or "azure"
  embeddings: "gemini" # or "azure"

######################### Optional Configuration #########################


# Vector Store Configuration
vector_store:
  index_path: "vector_store/faiss.index"
  metadata_path: "vector_store/metadata.pkl"

# Embedding Models Configuration
embeddings:
  # Azure OpenAI Embeddings
  azure:
    dimension: 1536
    chunk_size: 1000
  
  # Gemini Embeddings
  gemini:
    dimension: 768

# Language Models Configuration
llm:
  system_prompt: "You are a helpful assistant that answers questions based on the provided documentation."
  default_k: 3
  # Azure OpenAI LLM
  azure:
    temperature: 0.7
    max_tokens: 500
  
  # Gemini LLM
  gemini:
    temperature: 0.7
    top_p: 0.95
    max_output_tokens: 500

# Document Processing Configuration
document_loader:
  chunk_size: 300
  chunk_overlap: 15
  docs_directory: "docs"
  # directory of the pdf files that are scanned (images) and not proper text
  scanned_docs_dir: "scanned_docs"
  scanned_docs_lang: "ara" # language of the scanned documents
