# AI RAG System Configuration

######################### Mandatory Configuration #########################

# Azure OpenAI Configuration in case you want to use Azure OpenAI
azure:
  api_version: 2025-04-01-preview
  deployment: model
  embedding_deployment: text-embedding-3-small

# Gemini Configuration in case you want to use Gemini
gemini:
  model: gemini-2.5-pro
  embedding_model: models/embedding-001



# Vector Store Configuration
vector_store:
  index_path: "vector_store/faiss.index"
  metadata_path: "vector_store/metadata.pkl"


# Language Models Configuration
llm:
  # Provider Configuration
  # Set to 'azure' or 'gemini' to choose the AI provider you previsouly set (above)
  provider: "gemini"
  system_prompt: "You are a helpful assistant that answers questions based on the provided documentation. Reply in the same language as the question, unless otherwise specified."

  default_k: 20
  # Azure OpenAI LLM
  azure:
    temperature: 0.1
    max_tokens: 500
    embeddings_dimension: 1536
  
  # Gemini LLM
  gemini:
    temperature: 0.1
    top_p: 0.95
    max_output_tokens: 500
    embeddings_dimension: 768

# Document Processing Configuration
document_loader:
  chunk_size: 500
  chunk_overlap: 60
  docs_directory: "docs"
  # directory of the pdf files that are scanned (images) and not proper text
  ocr_docs_dir: "ocr_docs"
  llm_extractor_docs_dir: "llm_extractor_docs"
  scanned_docs_lang: "ara" # language of the scanned documents
