name: ai_rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - fastapi=0.118
  - uvicorn=0.37
  - python-dotenv=1.1.1
  - python-multipart=0.0.20
  - numpy<2
  - faiss-cpu==1.9
  - pytesseract
  - pdf2image
  - poppler
  - pillow
  - charset-normalizer=3.4.3
  - pip
  - pip:
      - numpy<2
      - langchain==0.3.27
      - langchain-community==0.3.30
      - langchain-text-splitters==0.3.11
      - langchain-openai==0.3.33
      - langchain-google-genai==2.1.12
      - pymupdf
      - unstructured[local-inference,pdf]==0.18.15
